### ISSUE TITLE
Accidentally exposed your "${SECRET_DOMAIN}:".

### ISSUE THREAD

**Issue by neverfind** [carpenike/k8s-gitops#2726]
I've spent the last two days studying your repo and config files, and plan to use it all as inspiration for my build. However, I noticed you used the variable ${SECRET_DOMAIN} and couldn't figured out where it was being referenced/created. I did however notice that you put the actual domain name in your NFS deployment file instead your usually variable. lol

Is it referenced in the encrypted cluster config secrets file?
`k8s/clusters/cluster-0/flux/vars/cluster-secrets.sops.yaml`

Did you deploy it like this for convenience, or were you actually trying to hide the domain name because I actually found a few places it's referenced directly instead of via a variable. 

```
k8s/clusters/cluster-0/pv/media/media-nfs-share.yaml
k8s/clusters/cluster-0/manifests/kasten-io/k10/helm-release.yaml
```

Would you mind adding me on discord for the occasional question about your setup?

**Comment by carpenike** [comment]
Hey @neverfind, very sorry for being so late to reply lol. Yes I'm generally much more active on Discord than here.

It was likely an oversight than anything else. It's not super important to me that the name not be available, but trying to move to a more modular/variable driven setup wherever possible.
