### ISSUE TITLE
Teleport: Changed chart value name

### ISSUE THREAD

**Issue by JoshuaGarrison27** [carpenike/k8s-gitops#3582]
Just a heads up while I was trying to use your chart as a reference, I found that this value might have changed in 11.2.0 so I thought I would give back and make you aware of it.

Changed from `existingClaim` to `existingClaimName`

Line in your code:
https://github.com/carpenike/k8s-gitops/blob/cf78f6f31f178ba09fd83caeba79d29932208e8a/cluster/clusters/cluster-0/teleport-cluster/teleport/cluster/helm-release.yaml#L35

Chart Values Reference:
https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L175

**Comment by carpenike** [comment]
thanks!
