### ISSUE TITLE
Typo existingCLaim in photoprism release.

### ISSUE THREAD

**Issue by Vaskozl** [carpenike/k8s-gitops#59]
The photoprism release has a typo on the key for originals :).

Thank you for making the chart.

**Comment by onedr0p** [comment]
@Vaskozl open a PR :)

**Comment by onedr0p** [comment]
oh nevermind, thought this was for the chart repo 🤣

**Comment by carpenike** [comment]
Thanks! Fixed in a5269478e5557bb9704ee24fdb02d995ec1ab6a0
